version: '3'

services:
  app:
    build:
      context: ./api
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000:5000"
      - "80:80"

  redis:
    image: redis
    volumes:
      - redis_data:/data

volumes:
  redis_data:
